### author : Toréa TESSIER <torea.tessier2@gmail.com>
# docker-compose verison to use
version: '3'

# Container's description
services:
  ## MySQL database
  database:
    image: torea/database
    # Restart the service if any issue happen
    restart: always

    # Uncomment to overload environment variables 
    # environment:
    #     TIMEZONE: Europe/Paris
    #     MYSQL_ROOT_PASSWORD: root
    #     MYSQL_DATABASE: app
    #     MYSQL_USER: app
    #     MYSQL_PASSWORD: app
    #     MYSQL_USER_MONITORING: monitoring
    #     MYSQL_PASSWORD_MONITORING: monitoring

  ## Web application
  webapp:
    # Link the app to the database
    depends_on:
      - database
    image: torea/webapp
    ports:
      - "8080:80"
    restart: always
    environment:
        DATABASE_IP: database

        # Uncoment to overload : 
        # APACHE_RUN_USER: www-data
        # APACHE_RUN_GROUP: www-data
        # APACHE_LOG_DIR: /var/log/apache2
